export {
  FileTextOutline,
  CheckCircleOutline,
  CheckCircleFill,
  CheckCircleTwoTone,
  InfoCircleOutline,
  CloseCircleOutline,
  ExclamationCircleOutline,
  CloseOutline,
  CopyOutline,
  LoadingOutline,
  PlusOutline,
  MinusOutline,
  EditOutline,
  DeleteOutline,
  ExclamationOutline,
  ExclamationCircleFill,
  SearchOutline,
  CloseCircleFill,
  DownOutline,
  SaveOutline,
  SettingOutline,
  // SmileOutline,
  // FrownOutline,
  CheckOutline,
  FileOutline,
  CodeOutline,
  LinkOutline,
} from '@ant-design/icons';
